### ISSUE TITLE
Add a better way to collect River sand

### ISSUE THREAD

**Issue by mickvangelderen** [mickvangelderen/graveyard-keeper-issue-tracker#30]
https://steamcommunity.com/app/599140/discussions/4/1734336452567525056/

Collecting it is fairly boring because you just stand still, hold a button for 8 real time minutes, occasionally pressing a different button to eat some food.

**Comment by ShaTiKus** [comment]
It's not so much about the process itself - in the end almost all gathering is 'press button wait' (having to extract it in one 'tick' with steel shovel would be nice tho). Rather it's about the sheer amount of sand needed for all glass-related stuff. Not to mention cleaning bloody nails, making polish paste and so on

**Comment by mickvangelderen** [comment]
The process of gathering and the amounts required in recipes are two different things that can be tweaked but both influence the balance of River sand production and usage. 

I need to try out embalming to get a feeling for the glass requirements for that. For the rest of the game it has been fine. I gathered sand for approximately two full days out of a 240 played.

I don't see the point of cleaning Bloody nails since Nails are super cheap anyway.

**Comment by mickvangelderen** [comment]
Version 1.026

> Sand gathering made much easier/faster.
