### ISSUE TITLE
Unreachable buildings when placed in certain locations

### ISSUE THREAD

**Issue by mickvangelderen** [mickvangelderen/graveyard-keeper-issue-tracker#5]
https://steamcommunity.com/app/599140/discussions/3/1734336452564036538/

![Unable to build, use or destroy the Distillery cube in this location](https://user-images.githubusercontent.com/5444990/44307249-566e5900-a39f-11e8-848c-b3b387d97ace.png)

**Comment by Provideniya** [comment]
Silly how you cant work them from behind. Duplicate of above, from the other side.
![gk_badplacement](https://user-images.githubusercontent.com/42512464/44308050-ec61ae00-a3b6-11e8-81b0-387eb99990b8.jpg)

**Comment by mickvangelderen** [comment]
https://steamcommunity.com/app/599140/discussions/4/1734336452569254343/

**Comment by mickvangelderen** [comment]
Version 1.026

> Instant removing of not-finished buildings (you can remove some stuck objects now).
